config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :products do
      resources :comments
  end
    
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'
    
  get 'static_pages/landing_page'
    
  resources :orders, only: [:index, :show, :create, :destroy]

  post 'static_pages/thank_you'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#landing_page'
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :orders
    has_many :comments
    validates :name, presence: true
    
    def highest_rating_comment
        comments.rating_desc.first
    end 
    
    def average_rating
        comments.average(:rating).to_f
    end
    
    
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if params[:q]
        search_term = params[:q]
        @products = Product.where("name LIKE ?", "%#{search_term}%")
    else
        @products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
  end

  # GET /products/new
  def new
    @products = Product.new
  end

  # GET /products/1/edit
  def edit
     
  end
    
  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :image_tag, :colour, :price)
    end

end

app/helpers/products_helper.rb
module ProductsHelper
    def cache_key_for_products
        count          = Product.count
        max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
        "products/all-#{count}-#{max_updated_at}"
    end
end

app/views/products/_comments.html.erb
<div class="product-reviews">
    <% @comments.each do |comment| %>
        <div class="row">
            <hr>
            <p><% comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
                <% if signed_in? && current_user.admin? %>
                    <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(comment.product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
                <% end %>
            </p>
            <p><%= "Rating: #{comment.rating}/5" %></p>
            <p><%= commment.body %></p>
        </div>
    <div class="rated" data-score="<%= comment.rating %>"></div>
    <% end%>
    <%= will_paginate @comments %>
</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="field">
      <%= f.label :colour %><br>
      <%= f.text_field :colour %>
  </div>

  <div class="field">
      <%= f.label :price %><br>
      <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

  <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
  </div>

  <div class="field">
      <label for="product_name">Name</label><br>
      <input id="product_name" name="product[name]" type="text" />
  </div>    

  <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description %>
  </div>

  <div class="actions">
      <%= f.submit %>
  </div>

<% end %>

    

app/views/products/_new_comment.html.erb
<% if signed_in? %>
    <h4>Leave a review:</h4>
    <%= form_for([@product, @product.comments.build], remote: true) do|if| %>
        <p>
            <%= f.label :body, "Comments" %><br>
            <%= f.text_area :body %>
        </p>
        <p>
            <div class="rating"></div>
        </p>
        <p>
            <%= f.submit "Submit" %>
        </p>
    <% end %>
<% end %>

app/views/products/_product.html.erb
<% cache product do %>       
<div class="col-sm-2 col-md-4">
        <h1><%= link_to product.name, product %></h1>
       <img><%= image_tag(product.image_url, class: "img-responsive") %>
       <p><%= product.description %></p>
       <p><%= product.color %></p>
       <strong>£<%= product.price %></strong>
   </div><!-- .col -->
        <% end %>
<% end %>

<%= @product.highest_rating_comment %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<div id="form">
<div class="form">
<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>
    
</div>
</div>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<!--
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Colour</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.image_url %></td>
        <td><%= product.colour %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
-->

<br>



<div class="container-fluid">
    <div class="row">
        <% @products.each do |product| %>
            <% cache(cache_key_for_products) do %>
                <%= render @product %>
        <% end %>
        <% end %>
    </div><!--.row -->
</div><!-- .container-fluid -->
<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<div class="form">
<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
    <div class="row" data-product-id="<%= @product.id %>">
        <div class="col-sm-2 col-md-4">
            <p>
                <% cache @product do %>
                    <strong>Name:</strong>
                    <%= @product.name %>
                <% end %>
            </p>
        </div>
        
        <div class="col-sm-3 col-md-4">
            <p>
                <strong>Description</strong>
                <%= @product.description %>
            </p>
        </div>
        
        <div class="col-sm-3 col-md-4">
            <p>
                <strong>Image url:</strong>
                <%= image_tag(@product.image_url, width "350", class: "img-zoom", data_zoom_image: ) %>
            </p>
        </div>
        
        <div class="col-sm-3 col-md-4">
            <p>
                <strong>Colour</strong>
                <%= @product.colour %>
            </p>
            <div id="#averate-rating">
                <p> Average Rating: <div class="rated" data-score="<%= @product.average_rating %>"> </div> 
            </div>
        </div>
        
        <div class="col-sm-3 col-md-4">
            <p>
                <strong>Price</strong>
                <%= @product.price %>
                
                <%= link_to 'Edit', edit_product_path(@product) %> |
                <%= link_to 'Back', products_path %>
            </p>
        </div>
        <div class="alert alert-info" style="display:none" role="alert">A new comment was posted!</div>
    <% if signed_in? %>
        <%= form_tag "/payments/create" do %>
        <%= hidden_field_tag(:product_id, @product.id) %>
    <%= render partial: "shared/stripe_checkout_button" %>
        <% end %>
    <% end %> 
    </div>
</div>