config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :products do
      resources :comments
  end
    
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'
    
  get 'static_pages/landing_page'
    
  resources :orders, only: [:index, :show, :create, :destroy]

  post 'static_pages/thank_you'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#landing_page'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nameofapp</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
      
    <meta name="viewport" content="width=device-width, initial scale=1">
    <%= csrf_meta_tags %>

  </head>

  <body>
     <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<%= static_pages_landing_page_path %>">Xenca <strong>Enerjii</strong></a>
        </div><!--/.navbar-header -->
    
        <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Home<span class="sr-only"></span></a></li>
                <li><a href="#about">About</a></li>
                <li><a href="#science">Science</a></li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Product Range<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#synerjii">Synerjii Classic</a></li>
                        <li><a href="#watch">Ladies Dual Band Tech Watch</a></li>
                        <li><a href="#bracelet">Sportii Bracelet</a></li>
                        <li><a href="#necklace">Sportii Necklace</a></li>
                    </ul>
                </li>
                <li><a href="#faq">FAQ</a></li>
                <li><a href="#contact">Contact</a></li>
            </ul>
            <ul class="nav pull-right">
                <li>
                    <% if user_signed_in? %>
                        <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
                    <% else %> 
                        <%= link_to('Login', new_user_session_path) %>
                    <% end %>
                </li>
            </ul>
            <%= form_tag("/products", method: "get", class: "navbar-form navbar-right", role: "search") do %>  
                <%= label_tag(:q, "Search for:") %>  
                <%= text_field_tag(:q) %>  
                <%= submit_tag("Search") %>  
            <% end %>  
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
      
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>  
    <% if notice %>
      <p id="notice" class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p id="alert" class="alert alert-info"><%= alert %></p>
    <% end %>
    
      <footer>
          <div class="container">
          &copy; 2016 Xenca Enerjii
          </div>
      </footer>
  </body>
</html>